server:
  port: 8080

logging:
  level:
    root: info

#security:
#  basic:
#    enabled: true    #启用SpringSecurity的安全配置项

#mybatis:
#  mapper-locations:                                     # 所有的mapper映射文件
#  - classpath*:/mybatis/**/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/TT_SSO?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT       # 数据库连接地址
    serverTimezone: GMT%2b8
    username: root                                  # 数据库用户名
    password: a132132                                # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true